version: 2.1
orbs:
  codecov: codecov/codecov@1.1.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/luklss/test-codev
    steps:
      - checkout
      - run: 
          command: |
              cd /go/src/github.com/luklss/test-codev/service1
              make test
      - codecov/upload:
          file: service1/coverage.txt
          flags: service1
      - run:
          command: |
              cd /go/src/github.com/luklss/test-codev/service2
              make test
      - codecov/upload:
          file: service2/coverage.txt
          flags: service2

